* numeri

Numeri is an Emacs Lisp package to support the conversion of [[https://en.wikipedia.org/wiki/Hindu–Arabic_numeral_system][Hindu-Arabic numbers]] to [[https://en.wikipedia.org/wiki/Roman_numerals][Roman]] and vice-versa. It is built off utility functions provided by the Org (~ox~) and reStructuredText (~rst~) packages. Only integer numbers are supported.

* Install

Install ~numeri~ from MELPA or MELPA stable (TBD). The commands in the package are auto-loaded so no changes are required in your initialization file.

If installed from source, you will need to require the package ~numeri~ in your Emacs initialization file.

#+begin_src elisp :lexical no
  (require 'numeri)
#+end_src

* Usage

There are two commands provided:

- ~numeri-arabic-to-roman~

  This command will accept either an Arabic integer number selected as a region or input via mini-buffer prompt and convert it to its Roman equivalent. The result is copied into the kill-ring.
  
- ~numeri-roman-to-arabic~

  This command will accept either a Roman integer number selected as a region or input via mini-buffer prompt and convert it to its Arabic equivalent. The result is copied into the kill-ring.

* Sponsorship
If you enjoy using Numeri, consider making a modest financial contribution to help support its development and maintenance.

[[https://www.buymeacoffee.com/kickingvegas][file:docs/images/default-yellow.png]]

* Acknowledgments
A heartfelt thanks to all the contributors of the Org and reStructuredText packages, whose work this package builds on top of.
  
